# Generated by Django 6.0.5 on 2026-06-04 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'matieres',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('filiere', models.CharField(choices=[('IA', 'Intelligence Artificielle'), ('IM', 'Internet des Objets et Multimédia'), ('GL', 'Génie Logiciel'), ('SE&IoT', 'Systèmes Embarqués & IoT'), ('SI', "Systèmes d'Information"), ('SIRI', "Systèmes d'Information et Réseaux Informatiques")], max_length=10)),
                ('niveau_etudes', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2'), ('Doctorat', 'Doctorat')], max_length=20)),
                ('photo_profil', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'indexes': [models.Index(fields=['filiere', 'niveau_etudes'], name='idx_filiere_niveau')],
            },
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id_conversation', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur1', models.ForeignKey(db_column='utilisateur1', on_delete=django.db.models.deletion.CASCADE, related_name='conv_user1', to=settings.AUTH_USER_MODEL)),
                ('utilisateur2', models.ForeignKey(db_column='utilisateur2', on_delete=django.db.models.deletion.CASCADE, related_name='conv_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'unique_together': {('utilisateur1', 'utilisateur2')},
            },
        ),
        migrations.CreateModel(
            name='Disponibilites',
            fields=[
                ('id_disponibilite', models.AutoField(primary_key=True, serialize=False)),
                ('jour_semaine', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=15)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disponibilites',
            },
        ),
        migrations.CreateModel(
            name='Matchings',
            fields=[
                ('id_matching', models.AutoField(primary_key=True, serialize=False)),
                ('score_compatibilite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_matching', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(db_column='id_mentor', on_delete=django.db.models.deletion.CASCADE, related_name='match_mentors', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(db_column='id_mentore', on_delete=django.db.models.deletion.CASCADE, related_name='match_mentores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matchings',
                'indexes': [models.Index(fields=['score_compatibilite'], name='idx_score_matching')],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contenu_message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='id_conversation', on_delete=django.db.models.deletion.CASCADE, to='mentorat.conversations')),
                ('expediteur', models.ForeignKey(db_column='id_expediteur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'indexes': [models.Index(fields=['date_envoi'], name='idx_date_message')],
            },
        ),
        migrations.CreateModel(
            name='ProfilCompetences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_competence', models.CharField(choices=[('fort', 'Point Fort'), ('faible', 'Point Faible')], max_length=10)),
                ('matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='mentorat.matieres')),
                ('utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profil_competences',
                'unique_together': {('utilisateur', 'matiere', 'type_competence')},
            },
        ),
        migrations.CreateModel(
            name='PropositionsMentorat',
            fields=[
                ('id_proposition', models.AutoField(primary_key=True, serialize=False)),
                ('type_proposition', models.CharField(choices=[('offre', 'Offre de mentorat'), ('demande', 'Demande de mentorat')], max_length=10)),
                ('format_session', models.CharField(choices=[('presentiel', 'Présentiel'), ('en ligne', 'En ligne'), ('les deux', 'Les deux')], max_length=15)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='mentorat.matieres')),
                ('utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'propositions_mentorat',
                'indexes': [models.Index(fields=['matiere'], name='idx_matiere'), models.Index(fields=['type_proposition'], name='idx_type_proposition')],
            },
        ),
    ]
