# Generated by Django 6.0.5 on 2026-06-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='filiere',
            field=models.CharField(choices=[('IA', 'Intelligence Artificielle'), ('IM', 'Internet et Multimédia'), ('GL', 'Génie Logiciel'), ('SE&IoT', 'Systèmes Embarqués & IoT'), ('SI', 'Sécurité Informatique'), ('SIRI', "Systèmes d'Information et Réseaux Informatiques")], max_length=10),
        ),
        migrations.CreateModel(
            name='MatiereFiliereNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(choices=[('IA', 'Intelligence Artificielle'), ('IM', 'Internet et Multimédia'), ('GL', 'Génie Logiciel'), ('SE&IoT', 'Systèmes Embarqués & IoT'), ('SI', 'Sécurité Informatique'), ('SIRI', "Systèmes d'Information et Réseaux Informatiques")], max_length=10)),
                ('niveau', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2'), ('Doctorat', 'Doctorat')], max_length=20)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorat.matieres')),
            ],
            options={
                'db_table': 'matiere_filiere_niveau',
                'unique_together': {('matiere', 'filiere', 'niveau')},
            },
        ),
    ]
