# Generated by Django 6.0.5 on 2026-06-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0002_alter_utilisateur_filiere_matierefiliereniveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='utilisateur1',
            field=models.ForeignKey(db_column='utilisateur1', on_delete=django.db.models.deletion.CASCADE, related_name='conv_user1', to='mentorat.utilisateur'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='utilisateur2',
            field=models.ForeignKey(db_column='utilisateur2', on_delete=django.db.models.deletion.CASCADE, related_name='conv_user2', to='mentorat.utilisateur'),
        ),
        migrations.AlterField(
            model_name='disponibilites',
            name='utilisateur',
            field=models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to='mentorat.utilisateur'),
        ),
        migrations.AlterField(
            model_name='matchings',
            name='mentor',
            field=models.ForeignKey(db_column='id_mentor', on_delete=django.db.models.deletion.CASCADE, related_name='match_mentors', to='mentorat.utilisateur'),
        ),
        migrations.AlterField(
            model_name='matchings',
            name='mentore',
            field=models.ForeignKey(db_column='id_mentore', on_delete=django.db.models.deletion.CASCADE, related_name='match_mentores', to='mentorat.utilisateur'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='expediteur',
            field=models.ForeignKey(db_column='id_expediteur', on_delete=django.db.models.deletion.CASCADE, to='mentorat.utilisateur'),
        ),
        migrations.AlterField(
            model_name='profilcompetences',
            name='utilisateur',
            field=models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to='mentorat.utilisateur'),
        ),
        migrations.AlterField(
            model_name='propositionsmentorat',
            name='utilisateur',
            field=models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, to='mentorat.utilisateur'),
        ),
    ]
