# Generated by Django 6.0.5 on 2026-06-08 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0002_alter_utilisateur_filiere_matierefiliereniveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReinitialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date_expiration', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codes_reinitialisation',
            },
        ),
    ]
